/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Describes the stream as it was actually opened. */
export interface AudioInfo {
  durationMs: number
  /**
   * Rate and layout the device was opened with. May differ from the source file if
   * the PCM had to be remapped or resampled.
   */
  sampleRate: number
  channels: number
  deviceName: string
  /** Frames per callback. `0` means the backend chose its own. */
  bufferFrames: number
  /** Theoretical latency of one buffer at this rate, in milliseconds. */
  bufferMs: number
  /** Samples that could not be decoded and were loaded as silence. */
  silentSamples: number
}

/** Everything a chart needs to be heard. */
export interface ChartAudioRequest {
  /** Background track, if the chart has one. A fully keysounded chart has none. */
  musicPath?: string
  /** Sound bank, in the order the chart's sample indices refer to. */
  samplePaths: Array<string>
  /** Sounds that play on schedule with no note attached. */
  scheduled: Array<ScheduledSoundInput>
  /** Chart length, used when there is no music to measure. */
  durationMs: number
}

/**
 * What a conversion produced. The chart itself goes to disk rather than across the
 * boundary: marshalling tens of thousands of notes into JavaScript objects would cost
 * far more than writing the file.
 */
export interface ChartSummary {
  id: string
  title: string
  artist: string
  difficultyName: string
  /** Key count. */
  columns: number
  noteCount: number
  holdCount: number
  /** Time of the last note, in milliseconds. */
  lastNoteMs: number
  tempoPoints: number
  scrollPoints: number
  sampleCount: number
  /** Audio file the chart refers to, relative to the chart file. */
  audioFile: string
  outputPath: string
}

/**
 * Converts an osu!mania `.osu` file into the game's chart format and writes it to
 * `outputPath` as JSON.
 *
 * Rejects charts that are not mode 3, and any chart that violates the format's
 * invariants — better to fail at import than to ship something the runtime misreads.
 */
export declare function convertOsuChart(sourcePath: string, outputPath: string): Promise<ChartSummary>

/** Sounds dropped because the trigger queue backed up. Should stay at zero. */
export declare function droppedSampleCount(): number

/**
 * Current audible position in milliseconds.
 *
 * Cheap by design — an atomic load and a subtraction — so it is safe to poll.
 */
export declare function getPositionMs(): number

/** Full playback snapshot. Returns zeroed values when nothing is loaded. */
export declare function getStats(): PlaybackStats

/**
 * True once the device is up to speed and `play()` will be heard immediately.
 *
 * Before that, a `play()` can take a couple of hundred milliseconds to become audible
 * because the backend is still bringing the stream up.
 */
export declare function isReady(): boolean

/**
 * Decodes `path` and leaves the device open, emitting silence.
 *
 * All of the start-up cost is paid here rather than on the first `play()`.
 */
export declare function loadAudio(path: string): Promise<AudioInfo>

/**
 * Loads a chart's music and sample bank together, and opens the device.
 *
 * Everything is mixed into one stream, so a keysound and the music share a latency.
 * Splitting them across outputs would make the game feel wrong however accurate its
 * judgement was.
 */
export declare function loadChartAudio(request: ChartAudioRequest): Promise<AudioInfo>

/** Starts playback of the loaded track. Audible within one buffer period. */
export declare function play(): void

/** A snapshot of playback state. */
export interface PlaybackStats {
  positionMs: number
  durationMs: number
  /** Output latency measured on the first armed callback. A snapshot, not live. */
  outputLatencyMs: number
  /** Manual calibration currently applied, in milliseconds. */
  offsetMs: number
  /** Real hardware sample rate over nominal. `1.0` until measured; diagnostic only. */
  rateRatio: number
  playing: boolean
  /** The device is up to speed, so starting playback will be heard immediately. */
  ready: boolean
  /** Sample voices sounding right now. Non-zero means the bank is actually playing. */
  activeVoices: number
  /** Sounds dropped because the trigger queue backed up. Should stay at zero. */
  droppedSamples: number
}

/**
 * Plays one sound from the bank straight away, at `volume` from 0 to 100.
 *
 * This is the path a keypress takes. It reaches the audio thread through a lock-free
 * queue, so it never blocks whoever called it and never stalls playback.
 */
export declare function playSample(sampleIndex: number, volume: number): void

/**
 * Returns to the beginning without reopening the device.
 *
 * `getPositionMs()` reports `0` from the moment this returns, rather than from when
 * the audio thread notices, so callers syncing to this clock cannot latch onto the
 * previous anchor.
 */
export declare function restart(): void

/** A sound the chart plays on its own, with no note to hit. */
export interface ScheduledSoundInput {
  timeMs: number
  /** Index into the sample paths given to `loadChartAudio`. */
  sample: number
  /** 0 to 100. */
  volume: number
}

/**
 * Manual calibration, in milliseconds.
 *
 * Positive means the audio is heard *later* than the clock reports, so the reported
 * position is pulled back to match. No API can know the real latency of the physical
 * output chain — Bluetooth headphones, an amplifier's DSP — so this has to be set by
 * the player. It is a no-op when nothing is loaded.
 */
export declare function setOffsetMs(offsetMs: number): void

/**
 * Closes the stream and releases the device.
 *
 * A later `play()` will fail: the track has to be loaded again. Always safe to call.
 */
export declare function unload(): void
