/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Describes the stream as it was actually opened. */
export interface AudioInfo {
  durationMs: number
  /**
   * Rate and layout the device was opened with. May differ from the source file if
   * the PCM had to be remapped or resampled.
   */
  sampleRate: number
  channels: number
  deviceName: string
  /** Frames per callback. `0` means the backend chose its own. */
  bufferFrames: number
  /** Theoretical latency of one buffer at this rate, in milliseconds. */
  bufferMs: number
}

/**
 * Current audible position in milliseconds.
 *
 * Cheap by design — an atomic load and a subtraction — so it is safe to poll.
 */
export declare function getPositionMs(): number

/** Full playback snapshot. Returns zeroed values when nothing is loaded. */
export declare function getStats(): PlaybackStats

/**
 * True once the device is up to speed and `play()` will be heard immediately.
 *
 * Before that, a `play()` can take a couple of hundred milliseconds to become audible
 * because the backend is still bringing the stream up.
 */
export declare function isReady(): boolean

/**
 * Decodes `path` and leaves the device open, emitting silence.
 *
 * All of the start-up cost is paid here rather than on the first `play()`.
 */
export declare function loadAudio(path: string): Promise<AudioInfo>

/** Starts playback of the loaded track. Audible within one buffer period. */
export declare function play(): void

/** A snapshot of playback state. */
export interface PlaybackStats {
  positionMs: number
  durationMs: number
  /** Output latency measured on the first armed callback. A snapshot, not live. */
  outputLatencyMs: number
  /** Manual calibration currently applied, in milliseconds. */
  offsetMs: number
  /** Real hardware sample rate over nominal. `1.0` until measured; diagnostic only. */
  rateRatio: number
  playing: boolean
  /** The device is up to speed, so starting playback will be heard immediately. */
  ready: boolean
}

/**
 * Returns to the beginning without reopening the device.
 *
 * `getPositionMs()` reports `0` from the moment this returns, rather than from when
 * the audio thread notices, so callers syncing to this clock cannot latch onto the
 * previous anchor.
 */
export declare function restart(): void

/**
 * Manual calibration, in milliseconds.
 *
 * Positive means the audio is heard *later* than the clock reports, so the reported
 * position is pulled back to match. No API can know the real latency of the physical
 * output chain — Bluetooth headphones, an amplifier's DSP — so this has to be set by
 * the player. It is a no-op when nothing is loaded.
 */
export declare function setOffsetMs(offsetMs: number): void

/**
 * Closes the stream and releases the device.
 *
 * A later `play()` will fail: the track has to be loaded again. Always safe to call.
 */
export declare function unload(): void
